

USE IMDB
GO

/**LENGUJE DE MANIPULACION DE DATOS**/

/*
	INSERT -> CREA O INSERTA UN NUEVO REGISTRO A LA TABLA 
	UPDATE -> ACTUALIZA UN NUEVO REGISTRO A LA TABLA
	DELETE -> ELIMINA UN REGISTRO
	SELECT -> CONSULTAR DATOS (NO ES DE MANIPULACION)
*/

SELECT * FROM MERCADEO.CONCEPTO
SELECT * FROM MERCADEO.AUTOR

INSERT INTO MERCADEO.AUTOR (NOMBRES, APELLIDOS, FECHA_NACIMIENTO, FECHA_DEFUNCION)
VALUES('DONALD', 'TRUMP', GETDATE(), GETDATE());


INSERT INTO MERCADEO.AUTOR (NOMBRES, APELLIDOS, FECHA_NACIMIENTO, FECHA_DEFUNCION)
VALUES('ROBERT', 'ROCKEFELLER', GETDATE(), GETDATE());


INSERT INTO MERCADEO.AUTOR (NOMBRES, APELLIDOS, FECHA_NACIMIENTO, FECHA_DEFUNCION)
VALUES('WILL', 'ROADSHILD', GETDATE(), GETDATE());


INSERT INTO MERCADEO.AUTOR (NOMBRES, APELLIDOS, FECHA_NACIMIENTO, FECHA_DEFUNCION)
VALUES(UPPER('jonh'), upper('smith'), GETDATE(), GETDATE());

-- SELECT UPPER('hola');
-- SELECT GETDATE() AS [HORA ACTUAL]
-- SELECT YEAR(GETDATE())
-- SELECT MONTH(GETDATE()) - 5 AS [RESTA]

SELECT * FROM MERCADEO.CONCEPTO

DECLARE @FECHA_LANZ AS DATETIME;
SET @FECHA_LANZ = (SELECT '19840614')

--SELECT @FECHA_LANZ

--SELECT GETDATE() - 30  AS FECHA

INSERT INTO MERCADEO.CONCEPTO(TITULO, RESENIA, FECHA_LANZAMIENTO, PAIS_ORIGEN, URL_WEB, ID_AUTOR)
VALUES('EL HOBBIT', 'ES UN CUENO FICTICIO INSPIRADO EN LA DEIDAD MEDIAVAL', @FECHA_LANZ, 'HONDURAS', 'https://portal.unitec.edu/', 1);	

SELECT * FROM MERCADEO.CONCEPTO

UPDATE MERCADEO.CONCEPTO
SET RESENIA = 'ES UN CUENTO FICTICIO INSPIRADO EN LA DEIDAD MEDIAVAL'
WHERE ID = 1

UPDATE MERCADEO.CONCEPTO
SET RESENIA = REPLACE(RESENIA, 'MEDIAVAL', 'MODERNA')
WHERE ID = 1


SELECT 



