USE master
GO

CREATE DATABASE IMDB

ON PRIMARY 
(
	NAME = 'IMDB_data', FILENAME = 'C:\Ceutec\TeoriaDeBasesDeDatos\S7\caso-1\databse-scripts\IMBD_data.mdf', SIZE = 10MB, MAXSIZE = UNLIMITED
)

LOG ON 
(
   NAME = 'IMDB_log', FILENAME = 'C:\Ceutec\TeoriaDeBasesDeDatos\S7\caso-1\databse-scripts\IMBD_log.ldf', SIZE = 5MB, MAXSIZE = 2GB
)

GO

USE IMDB
GO

CREATE SCHEMA MERCADEO;
CREATE SCHEMA NEGOCIO;
CREATE SCHEMA MISCELANEOS;


USE IMDB
GO

/* CREANDO UNA NUEVA TABLA*/

--DROP TABLE MERCADEO.AUTOR;

CREATE TABLE MERCADEO.AUTOR
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NOMBRES NVARCHAR(50) NOT NULL,
	APELLIDOS NVARCHAR(50) NOT NULL,
	FECHA_NACIMIENTO DATETIME,
	FECHA_DEFUNCION DATETIME,
	--PRIMARY KEY(ID)
)

CREATE TABLE MERCADEO.CONCEPTO
(
	ID INT IDENTITY(1,1) NOT NULL,
	TITULO NVARCHAR(100) NOT NULL,
	RESENIA NVARCHAR(MAX),
	FECHA_LANZAMIENTO DATETIME,
	PAIS_ORIGEN NVARCHAR(50),
	URL_WEB NVARCHAR(255),
	ID_AUTOR INT,
	PRIMARY KEY (ID)
)

ALTER TABLE MERCADEO.CONCEPTO
	WITH CHECK ADD CONSTRAINT FK_CONCEPTO_AUTOR
	FOREIGN KEY (ID_AUTOR)
	REFERENCES [MERCADEO].[AUTOR](ID)
	ON DELETE CASCADE

