USE master
GO

CREATE DATABASE IMDB

ON PRIMARY 
(
	NAME = 'IMDB_data', FILENAME = 'C:\Ceutec\TeoriaDeBasesDeDatos\S7\caso-1\databse-scripts\IMBD_data.mdf', SIZE = 10MB, MAXSIZE = UNLIMITED
)

LOG ON 
(
   NAME = 'IMDB_log', FILENAME = 'C:\Ceutec\TeoriaDeBasesDeDatos\S7\caso-1\databse-scripts\IMBD_log.ldf', SIZE = 5MB, MAXSIZE = 2GB
)

GO

USE IMDB
GO

CREATE SCHEMA MERCADEO;

CREATE SCHEMA NEGOCIO;

CREATE SCHEMA MISCELANEOS;


USE IMDB
GO

/* CREANDO UNA NUEVA TABLA*/

--DROP TABLE MERCADEO.AUTOR;

CREATE TABLE [MERCADEO].[AUTOR]
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NOMBRES NVARCHAR(50) NOT NULL,
	APELLIDOS NVARCHAR(50) NOT NULL,
	FECHA_NACIMIENTO DATETIME,
	FECHA_DEFUNCION DATETIME,
	--PRIMARY KEY(ID)
)

CREATE TABLE [MERCADEO].[CONCEPTO]
(
	ID INT IDENTITY(1,1) NOT NULL,
	TITULO NVARCHAR(100) NOT NULL,
	RESENIA NVARCHAR(MAX),
	FECHA_LANZAMIENTO DATETIME,
	PAIS_ORIGEN NVARCHAR(50),
	URL_WEB NVARCHAR(255),
	ID_AUTOR INT,
	PRIMARY KEY (ID)
)

ALTER TABLE MERCADEO.CONCEPTO
	WITH CHECK ADD CONSTRAINT FK_CONCEPTO_AUTOR
	FOREIGN KEY (ID_AUTOR)
	REFERENCES [MERCADEO].[AUTOR](ID)
	ON DELETE CASCADE


/*14/06/2018*/


CREATE TABLE [MERCADEO].[PRODUCCION] (
  [ID] INT IDENTITY(1,1) NOT NULL,
  [NOMBRE_COMPANIA] NVARCHAR(100),
  [PAIS] NVARCHAR(50),
  [URL_WEB] NVARCHAR(255),
  [CEO] NVARCHAR(100),
  PRIMARY KEY ([ID])
);

CREATE TABLE [NEGOCIO].[MEDIA] (
  [ID] INT IDENTITY(1,1) NOT NULL,
  [TITULO] NVARCHAR(100),
  [IDIOMA] NVARCHAR(50),
  [FORMATO] NVARCHAR(50),
  [FECHA_ESTRENO] DATETIME,
  [DURACION] TIME,
  [RESUMEN] NVARCHAR(MAX),
  [STORY_LINE] NVARCHAR(MAX),
  [AMAZON_URL] NVARCHAR(255),
  [SCORE_EXPERTOS] DECIMAL(1,1),
  [SCORE_USUARIOS] DECIMAL(1,1),
  [CANT_CAPITULOS] INT,
  [CANT_TEM] INT,
  [CANT_CAP] INT,
  [ARGUMENTO_JUEGO] NVARCHAR(MAX),
  [NUMERO_COMPILACION] NVARCHAR(7),
  [TIPO] NVARCHAR(15),
  [ID_CONCEPTO] INT,
  PRIMARY KEY ([ID])
);

ALTER TABLE [NEGOCIO].[MEDIA]
	WITH CHECK ADD CONSTRAINT FK_MEDIA_CONCEPTO
	FOREIGN KEY (ID_CONCEPTO)
	REFERENCES [MERCADEO].[CONCEPTO](ID)
	ON DELETE CASCADE;

CREATE TABLE [MERCADEO].[MEDIA_PRODUCCION] (
  [ID] INT IDENTITY(1,1) NOT NULL,
  [PORCENTAJE_APORTE] DECIMAL(18,2),
  [ID_MEDIA] INT,
  [ID_PRODUCCION] INT,
  PRIMARY KEY ([ID])
);

ALTER TABLE [MERCADEO].[MEDIA_PRODUCCION]
	WITH CHECK ADD CONSTRAINT FK_MED_PRO_PRODUCCION
	FOREIGN KEY (ID_PRODUCCION)
	REFERENCES [MERCADEO].[PRODUCCION](ID)
	ON DELETE CASCADE;
	
ALTER TABLE [MERCADEO].[MEDIA_PRODUCCION]
	WITH CHECK ADD CONSTRAINT FK_MED_PRO_MEDIA
	FOREIGN KEY (ID_MEDIA)
	REFERENCES [NEGOCIO].[MEDIA](ID)
	ON DELETE CASCADE;


CREATE TABLE [MERCADEO].[DATA_FINANCIERA] (
  [ID] INT IDENTITY(1,1) NOT NULL,
  [DESCRIPCION] NVARCHAR(100),
  [PAIS] NVARCHAR(50),
  [MONTO] MONEY,
  PRIMARY KEY ([ID])
);

CREATE TABLE [MERCADEO].[MEDIA_DATA_FINANCIERA] (
  [ID] INT IDENTITY(1,1) NOT NULL,
  [FECHAPUBLICACION] DATETIME,
  [ID_MEDIA] INT,
  [ID_DF] INT,
  PRIMARY KEY ([ID])
);

ALTER TABLE [MERCADEO].[MEDIA_DATA_FINANCIERA]
	WITH CHECK ADD CONSTRAINT FK_MED_DF_MEDIA
	FOREIGN KEY (ID_MEDIA)
	REFERENCES [NEGOCIO].[MEDIA](ID)
	ON DELETE CASCADE;

ALTER TABLE [MERCADEO].[MEDIA_DATA_FINANCIERA]
	WITH CHECK ADD CONSTRAINT FK_MED_DF_DATA_FINANC
	FOREIGN KEY (ID_DF)
	REFERENCES [MERCADEO].[DATA_FINANCIERA](ID)
	ON DELETE CASCADE;

CREATE TABLE [MERCADEO].[PRODUCTO_MARCA] (
  [ID] INT IDENTITY(1,1) NOT NULL,
  [DESCRIPCION] NVARCHAR(500),
  [MARCA] NVARCHAR(50),
  [TIPO] NVARCHAR(50),
  [ID_CONCEPTO] INT,
  PRIMARY KEY ([ID])
);

ALTER TABLE [MERCADEO].[PRODUCTO_MARCA]
	WITH CHECK ADD CONSTRAINT FK_PRO_MARCA_CONCEPTO
	FOREIGN KEY (ID_CONCEPTO)
	REFERENCES [MERCADEO].[CONCEPTO](ID)
	ON DELETE CASCADE;

CREATE TABLE [NEGOCIO].[FORMATO_MEDIA_JUEGO] (
  [ID] INT IDENTITY(1,1) NOT NULL,
  [FORMATO] NVARCHAR(50),
  [ID_MEDIA] INT,
  PRIMARY KEY ([ID])
);

ALTER TABLE [NEGOCIO].[FORMATO_MEDIA_JUEGO]
	WITH CHECK ADD CONSTRAINT FK_FORMATO_MED_JUE_MEDIA
	FOREIGN KEY (ID_MEDIA)
	REFERENCES [NEGOCIO].[MEDIA](ID)
	ON DELETE CASCADE;


CREATE TABLE [NEGOCIO].[PUESTOS] (
  [ID] INT IDENTITY(1,1) NOT NULL,
  [DESCRIPCION] NVARCHAR(MAX),
  [ES_GALARDONABLE] BIT,
  [ID_PADRE] INT,
  PRIMARY KEY ([ID])
);

-- OJO --
ALTER TABLE [NEGOCIO].[PUESTOS]
	WITH CHECK ADD CONSTRAINT FK_PUESTOS_PADRE
	FOREIGN KEY (ID_PADRE)
	REFERENCES [NEGOCIO].[PUESTOS] (ID)
	ON DELETE CASCADE;


CREATE TABLE [NEGOCIO].[ACTOR] (
  [ID] INT IDENTITY(1,1) NOT NULL,
  [NOMBRE_ARTISTICO] NVARCHAR(50),
  [SEXO] CHAR(2),
  [NOMBRE_REAL] NVARCHAR(50),
  [APELLIDO_REAL] NVARCHAR(50),
  [NACIONALIDAD] NVARCHAR(50),
  [DESCRIPCION] NVARCHAR(MAX),
  [FECHA_NACIMIENTO] DATETIME,
  [FECHA_DEFUNCON] DATETIME,
  PRIMARY KEY ([ID])
);

CREATE TABLE [NEGOCIO].[PUESTOS_ACTOR] (
  [ID] INT IDENTITY(1,1) NOT NULL,
  [DESCRIPCION] NVARCHAR(MAX),
  [ID_ACTOR] INT,
  [ID_PUESTO] INT,
  PRIMARY KEY ([ID])
);

ALTER TABLE [NEGOCIO].[PUESTOS_ACTOR]
	WITH CHECK ADD CONSTRAINT FK_PUESTOS_ACT_ACTOR
	FOREIGN KEY (ID_ACTOR)
	REFERENCES [NEGOCIO].[ACTOR](ID)
	ON DELETE CASCADE;

ALTER TABLE [NEGOCIO].[PUESTOS_ACTOR]
	WITH CHECK ADD CONSTRAINT FK_PUESTOS_ACT_PUESTOS
	FOREIGN KEY (ID_PUESTO)
	REFERENCES [NEGOCIO].[PUESTOS](ID)
	ON DELETE CASCADE;

CREATE TABLE [NEGOCIO].[REDES_SOCIALES] (
  [ID] INT IDENTITY(1,1) NOT NULL,
  [URL] NVARCHAR(100),
  [ICONO] NVARCHAR(MAX),
  [ID_MEDIA] INT,
  PRIMARY KEY ([ID])
);

ALTER TABLE [NEGOCIO].[REDES_SOCIALES]
	WITH CHECK ADD CONSTRAINT  FK_REDES_SOCIALES_MEDIA
	FOREIGN KEY (ID_MEDIA)
	REFERENCES [NEGOCIO].[MEDIA](ID)
	ON DELETE CASCADE;


CREATE TABLE [NEGOCIO].[MODO_JUEGO] (
  [ID] INT IDENTITY(1,1) NOT NULL,
  [DESCRIPCION] NVARCHAR(100),
  [ID_MEDIA] INT,
  PRIMARY KEY ([ID])
);


ALTER TABLE [NEGOCIO].[MODO_JUEGO]
	WITH CHECK ADD CONSTRAINT  FK_MODO_JUEGO_MEDIA
	FOREIGN KEY (ID_MEDIA)
	REFERENCES [NEGOCIO].[MEDIA](ID)
	ON DELETE CASCADE;


CREATE TABLE [NEGOCIO].[TRASESCENA] (
  [ID] INT IDENTITY(1,1) NOT NULL,
  [NOMBRES] NVARCHAR(50),
  [APELLIDOS] NVARCHAR(50),
  [PROFESION] NVARCHAR(50),
  [TIPO] NVARCHAR(20),
  [ID_MEDIA] INT,
  [ID_PUESTO] INT,
  PRIMARY KEY ([ID])
);

ALTER TABLE [NEGOCIO].[TRASESCENA]
	WITH CHECK ADD CONSTRAINT  FK_TRASESCENA_MEDIA
	FOREIGN KEY (ID_MEDIA)
	REFERENCES [NEGOCIO].[MEDIA](ID)
	ON DELETE CASCADE;


ALTER TABLE [NEGOCIO].[TRASESCENA]
	WITH CHECK ADD CONSTRAINT  FK_TRASESCENA_PUESTO
	FOREIGN KEY (ID_PUESTO)
	REFERENCES [NEGOCIO].[PUESTOS](ID)
	ON DELETE CASCADE;


CREATE TABLE [NEGOCIO].[PLATAFORMAS_MEDIA_JUEGO] (
  [ID] INT IDENTITY(1,1) NOT NULL,
  [DESCRIPCION] NVARCHAR(100),
  [ID_MEDIA] INT,
  PRIMARY KEY ([ID])
);

ALTER TABLE [NEGOCIO].[PLATAFORMAS_MEDIA_JUEGO]
	WITH CHECK ADD CONSTRAINT  FK_PLATAFORMAS_MEDIA_JUEGO_MEDIA
	FOREIGN KEY (ID_MEDIA)
	REFERENCES [NEGOCIO].[MEDIA](ID)
	ON DELETE CASCADE;

CREATE TABLE [NEGOCIO].[PERSONAJE] (
  [ID] INT IDENTITY(1,1) NOT NULL,
  [NOMBRES] NVARCHAR(50),
  [ALIAS] NVARCHAR(50),
  [DESCRIPCION] NVARCHAR(MAX),
  [SEXO] CHAR(2),
  [ESREAL] BIT,
  [REINO] NVARCHAR(50),
  PRIMARY KEY ([ID])
);

CREATE TABLE [NEGOCIO].[MEDIA_PERSONAJE] (
  [ID] INT IDENTITY(1,1) NOT NULL,
  [DESCRIPCION] NVARCHAR(MAX),
  [ID_MEDIA] INT,
  [ID_PERSONAJE] INT,
  PRIMARY KEY ([ID])
);

ALTER TABLE [NEGOCIO].[MEDIA_PERSONAJE]
	WITH CHECK ADD CONSTRAINT  FK_MEDIA_PERSONAJE_MEDIA
	FOREIGN KEY (ID_MEDIA)
	REFERENCES [NEGOCIO].[MEDIA](ID)
	ON DELETE CASCADE;


ALTER TABLE [NEGOCIO].[MEDIA_PERSONAJE]
	WITH CHECK ADD CONSTRAINT  FK_MEDIA_PERSONAJE_PERSONAJE
	FOREIGN KEY (ID_PERSONAJE)
	REFERENCES [NEGOCIO].[PERSONAJE](ID)
	ON DELETE CASCADE;

CREATE TABLE [NEGOCIO].[MEDIA_PAISES] (
  [ID] INT IDENTITY(1,1) NOT NULL,
  [NOMBRE_PAIS] NVARCHAR(50),
  [ID_MEDIA] INT,
  PRIMARY KEY ([ID])
);

ALTER TABLE [NEGOCIO].[MEDIA_PAISES]
	WITH CHECK ADD CONSTRAINT  FK_MEDIA_PAISES_MEDIA
	FOREIGN KEY (ID_MEDIA)
	REFERENCES [NEGOCIO].[MEDIA](ID)
	ON DELETE CASCADE;


CREATE TABLE [NEGOCIO].[PERSONAJE_ACTOR] (
  [ID] INT IDENTITY(1,1) NOT NULL,
  [DESCRIPCION] NVARCHAR(100),
  [ID_ACTOR] INT,
  [ID_PERSONAJE] INT,
  PRIMARY KEY ([ID])
);

ALTER TABLE [NEGOCIO].[PERSONAJE_ACTOR]
	WITH CHECK ADD CONSTRAINT FK_PERSONAJE_ACTOR_ACTOR
	FOREIGN KEY (ID_ACTOR)
	REFERENCES [NEGOCIO].[ACTOR](ID)
	ON DELETE CASCADE;

ALTER TABLE [NEGOCIO].[PERSONAJE_ACTOR]
	WITH CHECK ADD CONSTRAINT FK_PERSONAJE_PERSONAJE
	FOREIGN KEY (ID_PERSONAJE)
	REFERENCES [NEGOCIO].[PERSONAJE](ID)
	ON DELETE CASCADE;



/******MISCELANEOS******/



CREATE TABLE [MISCELANEOS].[CLASIFICACION] (
  [ID] INT IDENTITY(1,1) NOT NULL,
  [DESCRIPCION] NVARCHAR(MAX),
  [EDAD_MINIMA] INT,
  [ICONO] NVARCHAR(MAX),
  PRIMARY KEY ([ID])
);


CREATE TABLE [MISCELANEOS].[CONTENIDO_GRAFICO] (
  [ID] INT IDENTITY(1,1) NOT NULL,
  [TITULO] NVARCHAR(50),
  PRIMARY KEY ([ID])
);

CREATE TABLE [MISCELANEOS].[CONTENIDO_GRAFICO_MEDIA] (
  [ID] INT IDENTITY(1,1) NOT NULL,
  [DESCRIPCION] NVARCHAR(MAX),
  [ID_CLASIFICACION] INT,
  [ID_CONTGRAFICO] INT,
  [ID_MEDIA] INT,
  [NIVEL] NVARCHAR(20),
  PRIMARY KEY ([ID])
);


ALTER TABLE  [MISCELANEOS].[CONTENIDO_GRAFICO_MEDIA]
	WITH CHECK ADD CONSTRAINT  FK_CONTENIDO_GRAFICO_MEDIA_MEDIA
	FOREIGN KEY (ID_MEDIA)
	REFERENCES [NEGOCIO].[MEDIA](ID)
	ON DELETE CASCADE;

ALTER TABLE [MISCELANEOS].[CONTENIDO_GRAFICO_MEDIA]
	 WITH CHECK ADD CONSTRAINT FK_CONTENIDO_GRFICO_MEDIA_CLASIFICACION
	 FOREIGN KEY (ID_CLASIFICACION)
	 REFERENCES [MISCELANEOS].[CLASIFICACION] (ID)
	 ON DELETE CASCADE;

ALTER TABLE [MISCELANEOS].[CONTENIDO_GRAFICO_MEDIA]
	WITH CHECK ADD CONSTRAINT FK_CONTENIDO_GRFICO_MEDIA_CONT_GRAFICO
	 FOREIGN KEY ([ID_CONTGRAFICO])
	 REFERENCES [MISCELANEOS].[CONTENIDO_GRAFICO] (ID)
	 ON DELETE CASCADE;


CREATE TABLE [MISCELANEOS].[MEDIA_PALABRAS_CLAVE] (
  [ID] INT IDENTITY(1,1) NOT NULL,
  [PALABRA] NVARCHAR(50),
  [ID_MEDIA] INT,
  PRIMARY KEY ([ID])
);

ALTER TABLE  [MISCELANEOS].[MEDIA_PALABRAS_CLAVE]
	WITH CHECK ADD CONSTRAINT  FK_MEDIA_PALABRAS_CLAVE_MEDIA
	FOREIGN KEY (ID_MEDIA)
	REFERENCES [NEGOCIO].[MEDIA](ID)
	ON DELETE CASCADE;

CREATE TABLE [MISCELANEOS].[BANDA_SONORA] (
  [ID] INT IDENTITY(1,1) NOT NULL,
  [ARTISTA] NVARCHAR(50) NOT NULL,
  [ANIO] INT,
  [CANCION] NVARCHAR(100),
  [ID_MEDIA] INT,
  PRIMARY KEY ([ID])
);

ALTER TABLE  [MISCELANEOS].[BANDA_SONORA]
	WITH CHECK ADD CONSTRAINT  FK_BANDA_SONORA_MEDIA
	FOREIGN KEY (ID_MEDIA)
	REFERENCES [NEGOCIO].[MEDIA](ID)
	ON DELETE CASCADE;


CREATE TABLE [MISCELANEOS].[GENERO] (
  [ID] INT IDENTITY(1,1) NOT NULL,
  [TITULO] NVARCHAR(50),
  [DESCRIPCION] NVARCHAR(MAX),
  PRIMARY KEY ([ID])
);

CREATE TABLE [MISCELANEOS].[MEDIA_GENERO] (
  [ID] INT IDENTITY(1,1) NOT NULL,
  [ID_MEDIA] INT,
  [ID_GENERO] INT,
  PRIMARY KEY ([ID])
);


ALTER TABLE  [MISCELANEOS].[MEDIA_GENERO]
	WITH CHECK ADD CONSTRAINT  FK_MEDIA_GENERO_MEDIA
	FOREIGN KEY (ID_MEDIA)
	REFERENCES [NEGOCIO].[MEDIA](ID)
	ON DELETE CASCADE;


	ALTER TABLE  [MISCELANEOS].[MEDIA_GENERO]
	WITH CHECK ADD CONSTRAINT  FK_MEDIA_GENERO_GENERO
	FOREIGN KEY (ID_GENERO)
	REFERENCES [MISCELANEOS].[GENERO](ID)
	ON DELETE CASCADE;